theme: jekyll-theme-minimal
title: 💻✒🌟
description: 
title: <b>Contact</b><br>
        <p>Laan op Zuid 1340<br>3071AC,Rotterdam</p><br>
         <p>+0625361641</p><br>
         <p>zahari.tahiri@gmail.com </p><br>
         <p>12 februari 2003</p><br>
             <b>Hobby's</b><br>
             <p>Basketballen</p><br>
             <p>Voetballen</p><br>
             <p>Puzzelen</p><br>
             <p>Wandelen</p><br>
             <b>Talen</b><br>
             <p>Nederlands</p><br>
             <p>Engels</p><br>
             
             
