theme: jekyll-theme-minimal
title: 💻✒🌟
description: 
title: <b>Contact</b><br>
        <p>Laan op Zuid 1340<br>3071AC,Rotterdam</p>
             <b>Hobby's</b><br>
             <b>Talen</b><br>
             
             
